// <auto-generated />
using System;
using ApplicationStatusAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApplicationStatusAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250215074945_seed job")]
    partial class seedjob
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplicationStatusAPI.Models.JobApplication", b =>
                {
                    b.Property<int>("JobApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobApplicationId"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DateEdited")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateSubmitted")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.HasKey("JobApplicationId");

                    b.HasIndex("LocationId");

                    b.ToTable("JobApplications");

                    b.HasData(
                        new
                        {
                            JobApplicationId = 1,
                            CompanyName = "BidFood Limited",
                            DateSubmitted = new DateTime(2024, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobLink = "https://www.seek.co.nz/junior-.net-developer-jobs/in-All-Auckland?jobId=80539744&type=promoted",
                            JobTitle = "Software Developer",
                            LocationId = 1
                        });
                });

            modelBuilder.Entity("ApplicationStatusAPI.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            LocationName = "Auckland"
                        },
                        new
                        {
                            LocationId = 2,
                            LocationName = "Wellington"
                        },
                        new
                        {
                            LocationId = 3,
                            LocationName = "Christchurch"
                        },
                        new
                        {
                            LocationId = 4,
                            LocationName = "Hamilton"
                        },
                        new
                        {
                            LocationId = 5,
                            LocationName = "Tauranga"
                        },
                        new
                        {
                            LocationId = 6,
                            LocationName = "Dunedin"
                        });
                });

            modelBuilder.Entity("ApplicationStatusAPI.Models.JobApplication", b =>
                {
                    b.HasOne("ApplicationStatusAPI.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });
#pragma warning restore 612, 618
        }
    }
}
